// Boolean always return true or false
let number1 = 6;
let number2 = 4;
console.log(number1<number2); //false
console.log(number1>number2);  //true

// == vs === 
let num1 = "5";
let num2 = 5;
console.log(num1==num2); //true  == dose  check for the values not for data type
console.log(num1===num2); //false === checks for the both values and data type

//!= vs !==
console.log(num1 != num2); //false
console.log(num1 !== num2); //true
